apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-1
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nanajanashia/argocd-app:1.1
        ports:
        - containerPort: 8080
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: myapp-service-1
#spec:
#  selector:
#    app: myapp
#  ports:
#  - port: 8080
#    protocol: TCP
#    targetPort: 8080
  
